export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const INCREASE_BOOK_ITEM = "INCREASE_BOOK_ITEM";
export const DECREASE_BOOK_ITEM = "DECREASE_BOOK_ITEM";
export const DELETE_BOOK_ITEM = "DELETE_BOOK_ITEM";
export const ADD_BOOK_ITEM = "ADD_BOOK_ITEM";
